Class APG.ClassFive Extends %Persistent {

Storage Default
{
<Data name="ClassFiveDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^APG.ClassFiveD</DataLocation>
<DefaultData>ClassFiveDefaultData</DefaultData>
<IdLocation>^APG.ClassFiveD</IdLocation>
<IndexLocation>^APG.ClassFiveI</IndexLocation>
<StreamLocation>^APG.ClassFiveS</StreamLocation>
<Type>%Library.CacheStorage</Type>
}

}
