Class APG.ClassFour Extends %Persistent {


Storage Default
{
<Data name="ClassFourDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^APG.ClassFourD</DataLocation>
<DefaultData>ClassFourDefaultData</DefaultData>
<IdLocation>^APG.ClassFourD</IdLocation>
<IndexLocation>^APG.ClassFourI</IndexLocation>
<StreamLocation>^APG.ClassFourS</StreamLocation>
<Type>%Library.CacheStorage</Type>
}

}
