Class APG.ClassOne extends %Persistent {

Storage Default
{
<Data name="ClassOneDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^APG.ClassOneD</DataLocation>
<DefaultData>ClassOneDefaultData</DefaultData>
<IdLocation>^APG.ClassOneD</IdLocation>
<IndexLocation>^APG.ClassOneI</IndexLocation>
<StreamLocation>^APG.ClassOneS</StreamLocation>
<Type>%Library.CacheStorage</Type>
}

}